build:
  version: "1.0"

products:
  message: "Welcome to E-Commerce Online Shop Products microservice"
  contactDetails:
    name: "Rakhat Sultanaliuly"
    email: "{cipher}z/X/OrAwnPcLHbT3AlskTxsnSn35W3JF9ZRLsD1u2KA="
